BAD_REQUEST_RESPONSE = {"description": "Solicitud invalida"}
NOT_FOUND_RESPONSE = {"description": "Recurso no encontrado"}
INTERNAL_ERROR_RESPONSE = {"description": "Error interno del servidor"}

BAD_REQUEST_RESPONSES = {400: BAD_REQUEST_RESPONSE}
NOT_FOUND_RESPONSES = {404: NOT_FOUND_RESPONSE}
MODEL_INFO_RESPONSES = {
    404: NOT_FOUND_RESPONSE,
    500: INTERNAL_ERROR_RESPONSE,
}
TRAINING_RUN_RESPONSES = {
    400: BAD_REQUEST_RESPONSE,
    500: INTERNAL_ERROR_RESPONSE,
}
