sonar.projectKey=ajg1005_eeg-adhd-clasificacion
sonar.organization=ajg1005
sonar.projectName=eeg-adhd-clasificacion
sonar.projectVersion=1.0

sonar.sources=backend,frontend/src,scripts
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,**/.venv/**,**/.venv-tf/**,**/node_modules/**,**/dist/**,**/build/**,**/.pytest_cache/**,**/.ipynb_checkpoints/**,**/models/**,**/data/**,**/results/**,**/Figuras/**,**/*.joblib,**/*.keras,**/*.h5,**/*.csv

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml